
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int OPSUM = 9;
  public static final int PCL = 30;
  public static final int INCREMENT = 7;
  public static final int CONST = 17;
  public static final int POP = 29;
  public static final int CONSTENT = 4;
  public static final int CONSTBOOL = 3;
  public static final int SEMI = 31;
  public static final int EQUALWITHOPSUM = 5;
  public static final int AND = 12;
  public static final int FUN = 36;
  public static final int OR = 28;
  public static final int COMMA = 16;
  public static final int CODE = 15;
  public static final int IF = 22;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int EQUAL = 23;
  public static final int error = 1;
  public static final int BRACECL = 25;
  public static final int BRACEOP = 24;
  public static final int VOID = 34;
  public static final int GLOBALS = 21;
  public static final int BRACKETCL = 14;
  public static final int ARROW = 20;
  public static final int NO = 27;
  public static final int BRACKETOP = 13;
  public static final int ELSE = 18;
  public static final int SKIP = 33;
  public static final int WHILE = 35;
  public static final int OPMUL = 10;
  public static final int OPRELATIONAL = 8;
  public static final int END = 19;
  public static final int TYPEPRIM = 11;
  public static final int STRUCT = 26;
  public static final int EQUALWITHOPMUL = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CONSTBOOL",
  "CONSTENT",
  "EQUALWITHOPSUM",
  "EQUALWITHOPMUL",
  "INCREMENT",
  "OPRELATIONAL",
  "OPSUM",
  "OPMUL",
  "TYPEPRIM",
  "AND",
  "BRACKETOP",
  "BRACKETCL",
  "CODE",
  "COMMA",
  "CONST",
  "ELSE",
  "END",
  "ARROW",
  "GLOBALS",
  "IF",
  "EQUAL",
  "BRACEOP",
  "BRACECL",
  "STRUCT",
  "NO",
  "OR",
  "POP",
  "PCL",
  "SEMI",
  "RETURN",
  "SKIP",
  "VOID",
  "WHILE",
  "FUN"
  };
}

